### ISSUE TITLE
Could you make it support range requests? 

### ISSUE THREAD

**Issue by chaos369** [wader/ydls#187]
When you run ydls as http service, you may let user download by multi threads or watch the real time transcoded video.

**Comment by wader** [comment]
Hi! good question. If you use a format endpoint like `/mp3` ydls will always on-the-fly transmux and if needed also transcode the content. This is good as you get a response faster and you don't need to store things on the server. Problem is that we can't for most formats predict the exact final size of the file and even if we could most codecs can't easily be arbitrarily "chunked" at byte level like this. I can think of options to fix this also but it would involve storing and buffer large parts of the file and i'm also not sure if it would make things that much faster.

BTW ydls has support for doing time "range" request but that will cut the video, also that might also require downloading from the source to skip to the start position.

**Comment by chaos369** [comment]
Thank you for sharing the details. But what's the time "range" request? Do you meant something like m3u8? How Can I test the time "range" request?  Is it can be used to make the video playing skippable?  I think it is worthwhile to use caching for a better user experience.

**Comment by wader** [comment]
Sorry, i meant the "time" parameter documented here https://github.com/wader/ydls#parameters but that will seek and trim what to be encoded, so it will download and discard until the start point.

One way to do caching might be to have a caching http proxy in front of ydls, but not sure how caching servers will behave when caching things without a content-length for example.

**Comment by wader** [comment]
Don't think ydls will support range request any time soon, and i think it would require lot of work. Ok to close?
