### ISSUE TITLE
Stream youtube-dl -> ffmpeg

### ISSUE THREAD

**Issue by rudnypc** [wader/ydls#196]
Can you pass the youtube-dl stdout directly to ffmpeg and transmit it to the user?? This results in fast delivery of content.

**Comment by wader** [comment]
Hi, that is what ydls does, it always on-the-fly transcode/transmux from the source. What might take a bit of time in beginning for it starts it to figure what formats are available to know what combination matches the request best.

**Comment by wader** [comment]
Ok then you don't need ydls at all. This is how ydls will end up running youtube-dl https://github.com/wader/goutubedl/blob/master/goutubedl.go#L441 to make it stream. Note that you can run ydls as cli program also.

**Comment by rudnypc** [comment]
No, I need ydls, but my idea is to receive the video through an API

**Comment by wader** [comment]
If you want to know the details you can do `youtube-dl -J 'https://www.youtube.com/watch?v=ucZl6vQ_8Uo'` to get a dump what youtube-dl can provide.

**Comment by wader** [comment]
Hi again, did managed to get it working? close issue?
