### ISSUE TITLE
Bug in "Playlist as audio podcast with 3 latest items" mode without playlist-reverse

### ISSUE THREAD

**Issue by subvillion** [wader/ydls#268]
In debug mode generates this: `yt-dlp --ignore-errors --no-call-home --no-cache-dir --skip-download --restrict-filenames --batch-file - -J --yes-playlist --playlist-end 3`

but this gives oldest 3 files from playlist, not newest. Possible You forget `--playlist-reverse` param

**Comment by wader** [comment]
Hi, thanks for the report. Did some testing and i suspect that for youtube playlists yt-dlp will return items in the order they are in the playlist. I'm unsure if yt-dlp usually do any sorting by itself or not, i guess most playlist extractors does not and relay on the source instead.

Have some vague memory of trying to do sorting in ydls instead but one problem was that asking for the full playlist to be able to sort could be very slow because of how yt-dlp does it. Maybe thing have improved or there are some new options?

Could a workaround be to skip the "3 latest items"-option so that the rss feed includes all items? the pubDate seems to still be correct, but not sure how most podcast players will sort it.

**Comment by wader** [comment]
Forgot to say that we could off course add a `reverse` option or see if there is some hint in yt-dlp about ordering. But i'm curious what the end-goal is, to have a youtube playlist in a podcast player and when someone adds a new item (anywhere in the list?) to the playlist it should appear as new?

**Comment by wader** [comment]
Hey, did you look more into this? A reverse might be good idea to add

**Comment by subvillion** [comment]
My idea - put YT playlist to podcasts downloader, so I need latest "video" on top rss position.
I tryed to use full list without filtration, but its works to slow.

**Comment by wader** [comment]
Hi, did some tests to see what yt-dlp can provide with the youtube extractor and what could be possible to do:
```
# download playlist with end 3 
$ docker run --rm --entrypoint=yt-dlp mwader/ydls --yes-playlist -J --playlist-end 3  'https://www.youtube.com/watch?v=bagFAfFVruY&list=PL_QKjHDgmNzp7DA4KIR4qC-bjIVDlYdkk' > 3.json

# download playlist with end 3 and reverse
$ docker run --rm --entrypoint=yt-dlp mwader/ydls --yes-playlist -J --playlist-end 3 --playlist-reverse 'https://www.youtube.com/watch?v=bagFAfFVruY&list=PL_QKjHDgmNzp7DA4KIR4qC-bjIVDlYdkk' > 3-reverse.json4 

$ jq 'input_filename, (.entries[] | {title, upload_date, playlist_index, playlist_autonumber})' 3.json 3-reverse.json
"3.json"
{
  "title": "Check Yourself Before You Wreck Yourself Auditing and Improving the Performance of Boomerang",
  "upload_date": "20200708",
  "playlist_index": 1,
  "playlist_autonumber": 1
}
{
  "title": "From 0 to Intranet in 20 minutes with XWiki",
  "upload_date": "20200708",
  "playlist_index": 2,
  "playlist_autonumber": 2
}
{
  "title": "Welcome to FOSDEM 2020",
  "upload_date": "20200708",
  "playlist_index": 3,
  "playlist_autonumber": 3
}
"3-reverse.json"
{
  "title": "Welcome to FOSDEM 2020",
  "upload_date": "20200708",
  "playlist_index": 3,
  "playlist_autonumber": 1
}
{
  "title": "From 0 to Intranet in 20 minutes with XWiki",
  "upload_date": "20200708",
  "playlist_index": 2,
  "playlist_autonumber": 2
}
{
  "title": "Check Yourself Before You Wreck Yourself Auditing and Improving the Performance of Boomerang",
  "upload_date": "20200708",
  "playlist_index": 1,
  "playlist_autonumber": 3
}
```

Not sure if there are other yt-dlp options to make it behave differently but it seems like it returns the same 3 first entries in the playlist and reverse just reverses those. In the query above i included all the fields that are dates or have to do with ordering. To make reverse work the way we want i think we would have to fetch the whole playlist and then do some filtering and slicing in ydls.

Think i'm currently out of ideas how to solve this using yd-dl at least. Any other ideas?

**Comment by wader** [comment]
Closing for now. If yt-dlp can't provide enough info or is too slow for sorting like this then ydls probably have to do something on its own which is quite a bit of work. Feel free to reopen if you come up with some idea how to do it.
