### ISSUE TITLE
Issues with reverse proxy?

### ISSUE THREAD

**Issue by FoxxMD** [wader/ydls#279]
Hi, thanks for making this great tool!

I've got it to work using the docker build with my internal IP like so `http://192.168.x.xxx:8051/mp3/....`

However, after putting it behind a reverse proxy with nginx I am getting an error using the same URL: `https://ytcut.mydomain.me/mp3/...`

```
INFO: 13:13:35 172.17.0.1:43952 Downloading (mp3) https:/www.youtube.com/watch?v=3wg5UdoyswQ
INFO: 13:13:35 172.17.0.1:43952 Downloading (mp3) https:/www.youtube.com/watch?v=3wg5UdoyswQ
INFO: 13:13:41 172.17.0.1:43952 Download failed GET /mp3/https:/www.youtube.com/watch ([generic] Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given')))
```

This is what my reverse proxy block in nginx looks like:

```
server {
	listen 443 ssl http2;
	server_name ytcut.myDomain.me;
	
	location / {
        
        proxy_pass         http://192.168.x.xxx:8051/;
        auth_basic "Password Protected";
        auth_basic_user_file /config/nginx/.htpasswd;
  }
}
```

Any idea why I would be getting this error?

**Comment by wader** [comment]
Hey, thanks, glad to hear it's useful!

That is strange. Looking at the log it seems like the URL ydls gets to download is missing a "/" for the schema? some path/query rewrite going wrong?

**Comment by FoxxMD** [comment]
Removing the trailing slash from `proxy_pass` fixed the problem:

```
proxy_pass         http://192.168.x.xxx:8051;
```

If this is something you can detect and account for application-side I'd recommend doing it...the rest of my applications behind the reverse proxy all use a trailing slash, or don't seem to care one way or another if there is one.

**Comment by FoxxMD** [comment]
P.S. thanks again for making this. It's making it way easier for my friends/family to cut clips out of songs on youtube to make ringtones :) all of the existing websites i found were shady or didn't work. now i can just DIY :muscle:

**Comment by wader** [comment]
I was in the same situation :) also really wanted the RSS-thingy ydls can do. I use it mainly to turn random media websites into podcasts and mp3s.

Yeah maybe ydls could detect that the download URLs look fishy and warn? could also maybe have example in the README how to setup nginx etc?

Thanks again for the kind words!
