### ISSUE TITLE
http redirect

### ISSUE THREAD

**Issue by arg0nx** [wader/ydls#4]
Hi wader, great tool, just what I needed...

Is it possible to make it redirect to video link instead of starting download?

**Comment by wader** [comment]
Hello, thanks! not sure i follow what you want to do. You mean redirect to the "source" media? If so it might be possible in some cases where the source media is just one file but in most cases i would guess the source is some segmented or fragmented media source like, HLS, DASH etc in which case there is no single URL to direct to.

**Comment by wader** [comment]
Or do you mean play the media in the browser directly instead of download?

**Comment by arg0nx** [comment]
Sorry for insuficient details...
I'm unable to check now for links so I will just use examples...
When I input in VLC this link: http://MYserverIP:8080/http://youtube.com/watch?......
It play video from YT but through my server.
So the streams go from YT link "https://r2---sn-nx5e6n76.googlevideo.com/......" to my server and then to my local VLC
I would like that this can be redirected that I input link "http://MYserverIP:8080/http://youtube.com/watch?......" in VLC but vlc play it from https://r2---sn-nx5e6n76.googlevideo.com/......

If is impossible for DASH and HLS, maybe just for where media is jist one file as you said
I know vlc can play it directly but I took VLC just for example
Thanks

**Comment by wader** [comment]
Now i get it, thanks for explaining. Yes it might work in some cases.

For example take a look at what format youtube usually provide:
```sh
docker run --entrypoint=youtube-dl mwader/ydls -J https://www.youtube.com/watch?v=sX8r6zATHGU | jq .
```
You notice that all of them are either just audio or video, none of them are "muxed" together into one file. One of the features of ydls is that it actually supports downloading two streams and mux them into one while streaming.

So i guess it is possible to support this but i'm unsure how many sites it would work for.

**Comment by arg0nx** [comment]
Is it possible to explain how in few words if possible, i believe it might be done just in html? And yes, I'm using it for site that have audio and video muxed

**Comment by wader** [comment]
Hmm i'm a bit reluctant to this as it feels like a very specific case, but i might be wrong 😄 Is the problem cpu or network usage? i mean if it's done with ydls redirecting you will still need to have a ydls instance running anyway.

By HTML you mean doing it with HTML/JavaScript without involving ydls at all? it might be possible. I needs more details to be able to answer that.

**Comment by arg0nx** [comment]
Sure, but actually case is not specific ;)
I want to make m3u list for my smart tv for various sites, so for this I need ydls just to get valid link from YT or any other site that youtube dl supports when is needed

**Comment by wader** [comment]
But is the problem that the TV starts to download somehow instead of playing? i mean you can't really care if the stream goes thru ydls or not? then it could be because of the content-disposition attachment header etc that is used to make browsers download instead of open.

I know people have used ydls to play audio in HTML and it seems to work https://github.com/daohoangson/ydls-demo

**Comment by arg0nx** [comment]
Great, thank You :D

**Comment by wader** [comment]
Your welcome but i'm not sure how i helped to fix it 😄 it works if you use a `<video>` tag?

**Comment by arg0nx** [comment]
Same thing I need just with video, so I got clue what to look for

**Comment by wader** [comment]
Nice! good luck with your project!

**Comment by arg0nx** [comment]
Just one more quick question,
When I download movie using ydls does it stay on server or it is deleted afterwards?

**Comment by wader** [comment]
You mean the server where ydls is running? it does not stay on that server.
