### ISSUE TITLE
Add subtitle support

### ISSUE THREAD

**Issue by arg0nx** [wader/ydls#5]
Is it possible to execute additional commands like --write-subs for youtube-dl and --embed-subs for ffmpeg?

**Comment by wader** [comment]
Not possible at the moment. I don't have that much experience with how embed subtitles work in different container formats so i will need to do some research to figure how and if it would work.

**Comment by wader** [comment]
Did some research. It look promising but probably require quite a bit of changes, can't promise when i have time and energy to work on it.

**Comment by wader** [comment]
There is a experimental branch now with subtitles support if you want to try https://github.com/wader/ydls/pull/6
Seems to work kind of ok but the code is a bit messy
