### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by d7eeem** [wader/ydls#61]
Is there any way that you could release arm binaries?

**Comment by wader** [comment]
Hello! do you mean a ydls docker image for ARM or just ydls ARM binaries? 

Building ydls binaries should be more or less just clone the repo and do `GOOS=linux GOARCH=arm GOARM=5 go build ./cmd/ydls` and you get a ydls binary.

Docker image shouldn't be that much trouble either i think but i haven't worked with multi arch images, would be interesting. Also need to get a nice ffmpeg build for ARM. Have and experience with it?

**Comment by d7eeem** [comment]
> Have any experience with it?

Unfortunately no

**Comment by wader** [comment]
Image is now multi-arch amd64 and arm64. Other arm variants etc would require build with own ffmpeg binaries.
