### ISSUE TITLE
RSS fails if any playlist videos are private

### ISSUE THREAD

**Issue by adamcstephens** [wader/ydls#8]
ydls is already [ignoring errors](https://github.com/wader/ydls/blob/bea84d123eff799277b6df1b78b9d4c1c194f35f/internal/youtubedl/youtubedl.go#L437) which allows youtube-dl to successfully run in the case of private videos in a playlist.

Unfortunately, ydls still fails to load an rss feed if there is a private video. Perhaps because the youtube-dl info has nulls?

Example playlist (borrowed from https://github.com/ytdl-org/youtube-dl/issues/1594)
https://www.youtube.com/playlist?list=PLX0g748fkegS54oiDN4AXKl7BR7mLIydP

**Comment by wader** [comment]
Hi! thanks for reporting. On vacation at the moment but will have a look soon.

Tried `youtube-dl --no-call-home --no-cache-dir --skip-download --restrict-filenames -J --yes-playlist --ignore-errors 'https://www.youtub
e.com/playlist?list=PLX0g748fkegS54oiDN4AXKl7BR7mLIydP'` and it seems to work. So hopefully as easy as adding ignore option i hope.

**Comment by adamcstephens** [comment]
Thanks, enjoy your vacation!

**Comment by wader** [comment]
Fix in master now. Docker image should be done building soon.

**Comment by adamcstephens** [comment]
Sorry for the long delay on this.

Thanks again for the fix.

**Comment by wader** [comment]
@adamcstephens 👍
